<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>删除主体_1</name>
   <tag></tag>
   <elementGuidId>996f9a53-37a7-4a8e-b100-de0a1d6644a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ant-tree-node-content-wrapper.ant-tree-node-content-wrapper-normal > span.ant-tree-title > div.tree-node-text-line > div.node-tool > span.anticon.anticon-ellipsis.ant-dropdown-trigger > svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div/div/ul/li/span
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>64 64 896 896</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>ellipsis</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content _1M9q2B1DDgoOXtVE42bBZR pageMain&quot;]/div[1]/div[@class=&quot;_3EL9wyViIuJ_9tcu4-GtzO&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;left-tree&quot;]/div[@class=&quot;tree-area&quot;]/div[@class=&quot;ant-tree ant-tree-icon-hide&quot;]/div[@class=&quot;ant-tree-list&quot;]/div[@class=&quot;ant-tree-list-holder&quot;]/div[1]/div[@class=&quot;ant-tree-list-holder-inner&quot;]/div[@class=&quot;ant-tree-treenode ant-tree-treenode-switcher-close&quot;]/span[@class=&quot;ant-tree-node-content-wrapper ant-tree-node-content-wrapper-normal&quot;]/span[@class=&quot;ant-tree-title&quot;]/div[@class=&quot;tree-node-text-line&quot;]/div[@class=&quot;node-tool&quot;]/span[@class=&quot;anticon anticon-ellipsis ant-dropdown-trigger&quot;]/svg[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='手机号'])[1]/following::*[name()='svg'][1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='主体ID'])[1]/following::*[name()='svg'][2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='年龄'])[1]/preceding::*[name()='svg'][2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='姓名'])[1]/preceding::*[name()='svg'][4]</value>
   </webElementXpaths>
</WebElementEntity>
