<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__1</name>
   <tag></tag>
   <elementGuidId>6ac7b197-d32b-4f0a-b788-cdb7562f0ce6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.text-span.basic</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[5]/div/div/div/div[2]/div[1]/div/div/div[1]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-span basic</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>全部标签</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[1]/div[4]/div[1]/div[@class=&quot;ant-select-dropdown ant-tree-select-dropdown ant-select-dropdown-placement-bottomLeft&quot;]/div[1]/div[1]/div[@class=&quot;ant-select-tree&quot;]/div[@class=&quot;ant-select-tree-list&quot;]/div[@class=&quot;ant-select-tree-list-holder&quot;]/div[1]/div[@class=&quot;ant-select-tree-list-holder-inner&quot;]/div[@class=&quot;ant-select-tree-treenode ant-select-tree-treenode-switcher-open ant-select-tree-treenode-leaf-last&quot;]/span[@class=&quot;ant-select-tree-node-content-wrapper ant-select-tree-node-content-wrapper-normal&quot;]/span[@class=&quot;ant-select-tree-title&quot;]/div[@class=&quot;_3hxNV4KQLZrFk_XMampcwZ&quot;]/div[@class=&quot;node-text&quot;]/span[@class=&quot;text-span basic&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='标签描述'])[1]/following::span[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='是否唯一'])[1]/following::span[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='全部标签']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '全部标签' or . = '全部标签')]</value>
   </webElementXpaths>
</WebElementEntity>
